apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: backplane-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: system
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: backplane-operator
  template:
    metadata:
      labels:
        control-plane: backplane-operator
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: quay.io/stolostron/assisted-image-service@sha256:4b5aaf9ca9fe3f203b7dae19625c07f49f5fd6e13665e17f7d9213def22b7c00
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: quay.io/stolostron/assisted-installer@sha256:fd69ee3243727fff8c5dab1ba4b0c4e988595115170221a8a04dd7462e6c8592
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: quay.io/stolostron/assisted-installer-agent@sha256:750dfb0c09abaf92bb8d7c5ab61f01630a38768fdaa0ca5d9259360e6bf358be
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: quay.io/stolostron/assisted-installer-controller@sha256:4d94ca05d8187da3d8e0a3a51ca277b4ac41b639c648fa91a28fb3b4d883e1bd
        - name: OPERAND_IMAGE_ASSISTED_SERVICE
          value: quay.io/stolostron/assisted-service@sha256:e2b17522725a8cee676da2af8d2324cc4b8094b1ac5da90d165828e029b69967
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: quay.io/stolostron/backplane-must-gather@sha256:7789c8813c96b2ee9d3f6426966cbfc9789a8b689d376ac1b9b620854957d863
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: quay.io/stolostron/backplane-operator@sha256:a5ba328489646f83c3103ae9783570aef1abb745619509c891f89c416a6fdc55
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR_TEST
          value: quay.io/stolostron/backplane-operator-test@sha256:ae280181e1be837fd6ff1964f29a40e64523633df33f167e5ba7e6affd20a280
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: quay.io/stolostron/cluster-curator-controller@sha256:56e67466a558e1e0f0e135474393b04fa4b8eca92deb77cceb2cde0f2adf105c
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: quay.io/stolostron/clusterclaims-controller@sha256:8eb05dc8f85aba23859120e507bcd031e3fcde3149acde91a2100b2fcc0a5c5c
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: quay.io/stolostron/clusterlifecycle-state-metrics@sha256:dc16f478165941782601dadba8ea7364d03624f84da3cba9e93ace80833cb74e
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: quay.io/stolostron/console-mce@sha256:c3c5e9e616e830fb3c8e6a4766b2a76208c59260773d3edfa1cdd45564b66822
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: quay.io/stolostron/discovery-operator@sha256:702a5d26d2ef601b162d33ed269f489fad1746bb08a0c6f368af3a60f0d39b59
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR_TESTS
          value: quay.io/stolostron/discovery-operator-tests@sha256:a07af8b0b2d38fca12f588e3fa1c082d249180f9754bf0495b4bf6c8d7fc3594
        - name: OPERAND_IMAGE_DISCOVERY_TESTSERVER
          value: quay.io/stolostron/discovery-testserver@sha256:762f0bd1eea607ee9a1d56175a2ba00588ed4a013e78be3873a8cd92ebad6879
        - name: OPERAND_IMAGE_HELLOPROW_GO
          value: quay.io/stolostron/helloprow-go@sha256:e055ab3773a248c22dbde9847a3289e8512ccc85c6e9015544fc4f59d14b9cad
        - name: OPERAND_IMAGE_HELLOWORLD
          value: quay.io/stolostron/helloworld@sha256:dbf3e0c441f8462642d5e6c62fb5b80c5275cb73d93bd2637bc27a1edaeedbd3
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: quay.io/stolostron/hive@sha256:77893d60f8fe578ea87114d882daf27bab484ce55d221fb17ba77e1c78ad7024
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: quay.io/stolostron/managed-serviceaccount@sha256:09629112c3b45edacdf349e59bdb0a2650a13d2b09b989c12b5f0f9e85dd54fc
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT_E2E
          value: quay.io/stolostron/managed-serviceaccount-e2e@sha256:9e2ca32b8081d7b6b852d92c9906466cf7d7207a674106f132be549968b924f6
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: quay.io/stolostron/managedcluster-import-controller@sha256:2b67d186b332d7887fd69d98a66834c4a5e24009d1ea31b396b7f6e86f806ebc
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: quay.io/stolostron/multicloud-manager@sha256:999fe862ed3fb481bbbebcd075c19ad30a5c139a44d9e3eb21b1b5c6f67b3a37
        - name: OPERAND_IMAGE_PLACEMENT
          value: quay.io/stolostron/placement@sha256:eaa6c5dd90f782cd0a2bad8bf790f59dce0bbaeaaa627396fceea419f96c6b6d
        - name: OPERAND_IMAGE_POSTGRESQL_12
          value: quay.io/stolostron/postgresql-12-centos7@sha256:94727d70e0afbf4e167e078744f3a10ac9d82edc553d57b0ecbb5443264f07e1
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: quay.io/stolostron/provider-credential-controller@sha256:2e3048fb98be98d2af21987ebb6d9ac6cfb3ebb60b9ca5986f08ef091c4121b0
        - name: OPERAND_IMAGE_REGISTRATION
          value: quay.io/stolostron/registration@sha256:e7c631163bc2607ad286e366a04b0dd868e5ecdde9aae95955dbb87495e32238
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: quay.io/stolostron/registration-operator@sha256:6526476191280168ae1d9da0787075cb4656a135349f649575cdcba1bb250f5d
        - name: OPERAND_IMAGE_WORK
          value: quay.io/stolostron/work@sha256:04eb2d13d9987f10780960e201d870e245255cffa89af446e3311b004497dcd5
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: backplane-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
