apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: backplane-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: backplane-operator
  name: backplane-operator
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: backplane-operator
  template:
    metadata:
      labels:
        control-plane: backplane-operator
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /backplane-operator
        image: controller:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: backplane-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: backplane-operator
      terminationGracePeriodSeconds: 10
