kind: Deployment
apiVersion: apps/v1
metadata:
  name: hypershift-addon-manager
  labels:
    app: hypershift-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypershift-addon-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hypershift-addon-manager
        ocm-antiaffinity-selector: hypershift-addon-manager
    spec:
{{- if .PullSecret }}
      imagePullSecrets:
      - name: {{ .PullSecret }}
{{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - hypershift-addon-manager
          - weight: 35
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - hypershift-addon-manager
      restartPolicy: Always
      serviceAccountName: hypershift-addon-manager-sa
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-vol
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        # runAsUser: 1001
      terminationGracePeriodSeconds: 30
      containers:
        - name: hypershift-addon-manager
          image: {{index .Images hypershift_addon_operator }}
          volumeMounts:
          - mountPath: /tmp
            name: tmp-vol
          args:
            - ./hypershift-addon
            - manager
            - '--namespace={{ .Namespace }}'
            - '--with-image-override=true'
          env:
          - name: HYPERSHIFT_OPERATOR_IMAGE_NAME
            value: '{{index .Images hypershift_operator }}'
          - name: HYPERSHIFT_ADDON_IMAGE_NAME
            value: '{{index .Images hypershift_addon_operator }}'
          - name: KUBE_RBAC_PROXY_IMAGE_NAME
            value: '{{index .Images kube_rbac_proxy_mce }}'
{{- if .ProxyConfigs }}
        - name: HTTP_PROXY
          value: {{index .ProxyConfigs "HTTP_PROXY" }}
        - name: HTTPS_PROXY
          value: {{index .ProxyConfigs "HTTPS_PROXY" }}
        - name: NO_PROXY
          value: {{index .ProxyConfigs "NO_PROXY" }}
{{- end }}
          imagePullPolicy: {{ .PullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "2m"
              memory: "2Mi"
{{- if .NodeSelector }}
      nodeSelector:
{{- range $key, $value := .NodeSelector }}
        {{$key}}: "{{$value}}"
      {{- end }}
{{- end }}
{{- with .Tolerations }}
      tolerations:
      {{- range . }}
      - {{ if .Key }} key: {{ .Key }} {{- end }}
        {{ if .Operator }} operator: {{ .Operator }} {{- end }}
        {{ if .Value }} value: {{ .Value }} {{- end }}
        {{ if .Effect }} effect: {{ .Effect }} {{- end }}
        {{ if .TolerationSeconds }} tolerationSeconds: {{ .TolerationSeconds }} {{- end }}
      {{- end }}
{{- end }}
