
# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Org }}.cluster-lifecycle.cluster-image-set
subjects:
- kind: ServiceAccount
  name: cluster-image-set
  namespace: {{ .Namespace }}       ## CHANGE: ACM namespace
roleRef:
  kind: ClusterRole
  name: {{ .Org }}.cluster-lifecycle.cluster-image-set
  apiGroup: rbac.authorization.k8s.io
