# permissions for end users to view backplaneconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplaneconfig-viewer-role
rules:
- apiGroups:
  - backplane.open-cluster-management.io
  resources:
  - backplaneconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backplane.open-cluster-management.io
  resources:
  - backplaneconfigs/status
  verbs:
  - get
