apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: '{{ .Org }}:discovery-operator:discovery-operator-metrics-reader'
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
