# Copyright Contributors to the Open Cluster Management project
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Org }}:console-mce:clusterrolebinding
subjects:
- kind: ServiceAccount
  name: console-mce
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Org }}:console-mce:clusterrole
  apiGroup: rbac.authorization.k8s.io
