# Copyright Contributors to the Open Cluster Management project

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Org }}:server-foundation:managedcluster-import-controller-v2
subjects:
- kind: ServiceAccount
  name: managedcluster-import-controller-v2
  namespace: '{{ .Namespace }}'
roleRef:
  kind: ClusterRole
  name: {{ .Org }}:server-foundation:managedcluster-import-controller-v2
  apiGroup: rbac.authorization.k8s.io