apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-proxyserver
spec:
  replicas: {{ .ReplicaCount }}
  selector:
    matchLabels:
      control-plane: ocm-proxyserver
      ocm-antiaffinity-selector: ocm-proxyserver
  template:
    metadata:
      labels:
        control-plane: ocm-proxyserver
        ocm-antiaffinity-selector: ocm-proxyserver
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - ocm-proxyserver
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - ocm-proxyserver
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - /proxyserver
        - --secure-port=6443
        - --tls-cert-file=/var/run/apiservice/tls.crt
        - --tls-private-key-file=/var/run/apiservice/tls.key
        - --agent-cafile=/var/run/klusterlet/ca.crt
        - --agent-certfile=/var/run/klusterlet/tls.crt
        - --agent-keyfile=/var/run/klusterlet/tls.key
        env:
{{- if .ProxyConfigs }}
        - name: HTTP_PROXY
          value: {{index .ProxyConfigs "HTTP_PROXY" }}
        - name: HTTPS_PROXY
          value: {{index .ProxyConfigs "HTTPS_PROXY" }}
        - name: NO_PROXY
          value: {{index .ProxyConfigs "NO_PROXY" }}
{{- end }}
        - name: GOMEMLIMIT
          value: "2750MiB"
        image: '{{index .Images multicloud_manager }}'
        imagePullPolicy: {{ .PullPolicy }}
        name: ocm-proxyserver
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 3Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/run/klusterlet
          name: klusterlet-certs
        - mountPath: /var/run/apiservice
          name: apiservice-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: ocm-foundation-sa
      serviceAccountName: ocm-foundation-sa
      terminationGracePeriodSeconds: 30
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- if .PullSecret }}
      imagePullSecrets:
      - name: {{ .PullSecret }}
{{- end }}
{{- if .NodeSelector }}
      nodeSelector:
{{- range $key, $value := .NodeSelector }}
        {{$key}}: "{{$value}}"
      {{- end }}
{{- end }}
{{- with .Tolerations }}
      tolerations:
      {{- range . }}
      - {{ if .Key }} key: {{ .Key }} {{- end }}
        {{ if .Operator }} operator: {{ .Operator }} {{- end }}
        {{ if .Value }} value: {{ .Value }} {{- end }}
        {{ if .Effect }} effect: {{ .Effect }} {{- end }}
        {{ if .TolerationSeconds }} tolerationSeconds: {{ .TolerationSeconds }} {{- end }}
      {{- end }}
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ocm-foundation-sa
      volumes:
      - name: klusterlet-certs
        secret:
          defaultMode: 420
          secretName: ocm-klusterlet-self-signed-secrets
      - name: apiservice-certs
        secret:
          defaultMode: 420
          secretName: ocm-proxyserver