# Copyright Contributors to the Open Cluster Management project

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-manager-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-manager
  source: community-operators
  sourceNamespace: openshift-marketplace