apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-manager
  strategy: {}
  template:
    metadata:
      labels:
        app: cluster-manager
        ocm-antiaffinity-selector: cluster-manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - cluster-manager
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - cluster-manager
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - /registration-operator
        - hub
        env:
{{- if .ProxyConfigs }}
        - name: HTTP_PROXY
          value: {{index .ProxyConfigs "HTTP_PROXY" }}
        - name: HTTPS_PROXY
          value: {{index .ProxyConfigs "HTTPS_PROXY" }}
        - name: NO_PROXY
          value: {{index .ProxyConfigs "NO_PROXY" }}
{{- end }}
        image: '{{index .Images registration_operator }}'
        imagePullPolicy: {{ .PullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 10
        name: registration-operator
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- if .PullSecret }}
      imagePullSecrets:
      - name: {{ .PullSecret }}
{{- end }}
{{- if .NodeSelector }}
      nodeSelector:
{{- range $key, $value := .NodeSelector }}
        {{$key}}: "{{$value}}"
      {{- end }}
{{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cluster-manager
{{- with .Tolerations }}
      tolerations:
      {{- range . }}
      - {{ if .Key }} key: {{ .Key }} {{- end }}
        {{ if .Operator }} operator: {{ .Operator }} {{- end }}
        {{ if .Value }} value: {{ .Value }} {{- end }}
        {{ if .Effect }} effect: {{ .Effect }} {{- end }}
        {{ if .TolerationSeconds }} tolerationSeconds: {{ .TolerationSeconds }} {{- end }}
      {{- end }}
{{- end }}
